---
- hosts: webserver
  become: yes
  tasks:
  - name: i want to install webserver on RHEL
    yum: 
      name: "{{webserverforredhat}}"
      state: present
  - name: start the httpd service after installing
    service:
      name: "{{webserverforredhat}}"
      state: started
 