---
- name: crating a j2 file
  file:
    name: j2file
    path: /home/raj/
    state: touch

- name: replacing my contect on webserver
  template:
    src: content.j2
    dest: /var/www/html/index.html